"""StellarCode login for DevFlow (web-approved device flow).

Flow (server: StellarCode Studio ``/api/mcp-connect``):

    devflow  POST /api/mcp-connect/iniciar  -> device_code (secret) + user_code + verification_path
    person   opens the web link, signs in (Google, GitHub or password + MFA) and approves
    devflow  POST /api/mcp-connect/token    -> 202 pending ... 200 {token, mcp_url, expires_in_hours}

The short-lived MCP token is stored outside every repository, in ``$DEVFLOW_HOME`` (default
``~/.devflow``) with 0600 permissions, using the same ``stellar[-<profile>].env`` format that
StellarCode Studio's ``npm run devflow:login`` writes. It is never written to ``.devflow.yml``.
"""
from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.parse
import urllib.request

from . import __version__
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Callable

DEFAULT_API_URL = "https://api.stellarcodelabs.lat"
DEFAULT_WEB_URL = "https://app.stellarcodelabs.lat"
DEV_API_URL = "http://localhost:3010"
DEV_WEB_URL = "http://localhost:3011"
# Identificación honesta de la CLI: el User-Agent por defecto de urllib (Python-urllib/x) lo bloquea Cloudflare (error 1010) en api.stellarcodelabs.lat.
USER_AGENT = f"devflow-cli/{__version__} (+https://github.com/mathiasmora2232/DevFlow)"

TOKEN_ENV_CANDIDATES = ("STELLARCODE_TOKEN", "STELLAR_MCP_TOKEN")
EXPIRY_MARGIN = timedelta(seconds=60)


class StellarAuthError(RuntimeError):
    pass


HttpFn = Callable[[str, dict[str, Any]], tuple[int, dict[str, Any]]]


def _now() -> datetime:
    return datetime.now(timezone.utc)


def devflow_home() -> Path:
    return Path(os.getenv("DEVFLOW_HOME") or Path.home() / ".devflow").expanduser()


def resolve_profile(profile: str | None = None) -> str:
    value = profile if profile is not None else os.getenv("STELLAR_ENV", "")
    value = (value or "").strip().lower()
    return "" if value in {"", "prod", "production"} else value


def credentials_path(profile: str | None = None) -> Path:
    p = resolve_profile(profile)
    return devflow_home() / f"stellar{'-' + p if p else ''}.env"


def pending_path(profile: str | None = None) -> Path:
    p = resolve_profile(profile)
    return devflow_home() / f"stellar{'-' + p if p else ''}.pending.json"


def default_urls(profile: str | None = None) -> tuple[str, str]:
    dev = resolve_profile(profile) == "dev"
    api = os.getenv("STELLAR_API_URL") or (DEV_API_URL if dev else DEFAULT_API_URL)
    web = os.getenv("STELLAR_WEB_URL") or (DEV_WEB_URL if dev else DEFAULT_WEB_URL)
    return api.rstrip("/"), web.rstrip("/")


def api_base_from_mcp_url(mcp_url: str | None) -> str | None:
    if not mcp_url:
        return None
    url = mcp_url.rstrip("/")
    return url[: -len("/mcp")] if url.endswith("/mcp") else url


def _write_private(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(path.parent, 0o700)
    except OSError:
        pass
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(content)
    try:
        os.chmod(path, 0o600)
    except OSError:  # Windows
        pass


def _parse_iso(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)


# ── credential store ──────────────────────────────────────────────────────────

def save_credentials(token: str, mcp_url: str, expires_at: datetime, profile: str | None = None) -> Path:
    if "'" in token or "\n" in token:
        raise StellarAuthError("Refusing to store a malformed token.")
    path = credentials_path(profile)
    expires = expires_at.astimezone(timezone.utc).isoformat().replace("+00:00", "Z")
    _write_private(path, (
        "# Generated by `devflow stellar-login`. Do not commit this file.\n"
        f"export STELLAR_MCP_TOKEN='{token}'\n"
        f"export STELLAR_MCP_URL='{mcp_url}'\n"
        f"export STELLAR_MCP_TOKEN_EXPIRES='{expires}'\n"
    ))
    return path


def load_credentials(profile: str | None = None) -> dict[str, Any] | None:
    path = credentials_path(profile)
    if not path.is_file():
        return None
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        key, sep, value = line.partition("=")
        if sep:
            values[key.strip()] = value.strip().strip("'\"")
    token = values.get("STELLAR_MCP_TOKEN")
    if not token:
        return None
    return {
        "token": token,
        "mcp_url": values.get("STELLAR_MCP_URL"),
        "expires_at": _parse_iso(values.get("STELLAR_MCP_TOKEN_EXPIRES")),
        "path": str(path),
    }


def clear_credentials(profile: str | None = None) -> list[Path]:
    removed = []
    for path in (credentials_path(profile), pending_path(profile)):
        if path.exists():
            path.unlink()
            removed.append(path)
    return removed


def is_expired(creds: dict[str, Any], now: datetime | None = None) -> bool:
    expires = creds.get("expires_at")
    return bool(expires and (now or _now()) >= expires - EXPIRY_MARGIN)


@dataclass
class TokenResolution:
    token: str | None
    source: str | None
    mcp_url: str | None = None
    expires_at: datetime | None = None
    expired_path: str | None = None


def resolve_token(token_env: str | None = None, profile: str | None = None) -> TokenResolution:
    """Environment variables win (CI/service accounts); then the local login store."""
    names = [token_env] if token_env else []
    names += [n for n in TOKEN_ENV_CANDIDATES if n not in names]
    for name in names:
        value = os.getenv(name, "").strip()
        if value:
            return TokenResolution(value, f"env:{name}")
    creds = load_credentials(profile)
    if creds:
        if is_expired(creds):
            return TokenResolution(None, None, creds.get("mcp_url"), creds.get("expires_at"), creds["path"])
        return TokenResolution(creds["token"], f"file:{creds['path']}", creds.get("mcp_url"), creds.get("expires_at"))
    return TokenResolution(None, None)


def auth_status(token_env: str | None = None, profile: str | None = None, now: datetime | None = None) -> dict[str, Any]:
    res = resolve_token(token_env, profile)
    now = now or _now()
    status: dict[str, Any] = {
        "authenticated": bool(res.token),
        "source": res.source,
        "mcp_url": res.mcp_url,
        "expires_at": res.expires_at.isoformat() if res.expires_at else None,
        "remaining_minutes": None,
        "profile": resolve_profile(profile) or "prod",
        "credentials_path": str(credentials_path(profile)),
    }
    if res.expires_at:
        status["remaining_minutes"] = max(0, int((res.expires_at - now).total_seconds() // 60))
    if res.expired_path:
        status["reason"] = "expired"
    elif not res.token:
        status["reason"] = "missing"
    pending = load_pending(profile)
    if pending and not res.token:
        status["pending_login"] = {k: pending[k] for k in ("user_code", "login_url", "approve_url", "expires_at") if k in pending}
    return status


# ── device flow ───────────────────────────────────────────────────────────────

def http_post_json(url: str, body: dict[str, Any], timeout: float = 20.0) -> tuple[int, dict[str, Any]]:
    data = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(url, data=data, method="POST", headers={"content-type": "application/json", "accept": "application/json", "user-agent": USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310 - fixed https endpoints
            status, raw = resp.status, resp.read()
    except urllib.error.HTTPError as exc:
        status, raw = exc.code, exc.read()
    except (urllib.error.URLError, OSError) as exc:
        raise StellarAuthError(f"Could not reach {url}: {getattr(exc, 'reason', exc)}") from exc
    try:
        payload = json.loads(raw.decode("utf-8") or "{}")
    except (ValueError, UnicodeDecodeError):
        payload = {"raw": raw[:200].decode("utf-8", "replace")}
    return status, payload if isinstance(payload, dict) else {"data": payload}


def login_urls(web_url: str, verification_path: str) -> dict[str, str]:
    web = web_url.rstrip("/")
    return {
        # Already signed in on the web: lands directly on "Continue as <you>".
        "approve_url": f"{web}{verification_path}",
        # Not signed in: login page with Google/GitHub/password that returns to the approval screen.
        "login_url": f"{web}/login?redirect={urllib.parse.quote(verification_path, safe='')}",
    }


def start_login(
    *,
    api_url: str,
    web_url: str,
    client_name: str,
    hours: int = 24,
    profile: str | None = None,
    http: HttpFn = http_post_json,
    now: datetime | None = None,
) -> dict[str, Any]:
    hours = min(max(int(hours), 1), 24)
    status, body = http(f"{api_url.rstrip('/')}/api/mcp-connect/iniciar", {"nombre": client_name, "horas": hours})
    if status not in (200, 201) or not body.get("device_code"):
        raise StellarAuthError(f"StellarCode refused to start the login (HTTP {status}): {body.get('error') or body}")
    expires_in = int(body.get("expires_in") or 600)
    pending = {
        "device_code": body["device_code"],
        "user_code": body.get("user_code"),
        "interval": int(body.get("interval") or 2),
        "expires_at": ((now or _now()) + timedelta(seconds=expires_in)).isoformat(),
        "api_url": api_url.rstrip("/"),
        "web_url": web_url.rstrip("/"),
        "client_name": client_name,
        "hours": hours,
        **login_urls(web_url, body.get("verification_path") or ""),
    }
    _write_private(pending_path(profile), json.dumps(pending, indent=2))
    return pending


def load_pending(profile: str | None = None) -> dict[str, Any] | None:
    path = pending_path(profile)
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except ValueError:
        return None
    expires = _parse_iso(data.get("expires_at"))
    if expires and _now() >= expires:
        path.unlink(missing_ok=True)
        return None
    return data


def public_ticket(pending: dict[str, Any]) -> dict[str, Any]:
    """What may be shown to a person or an agent: never the device_code."""
    return {k: v for k, v in pending.items() if k != "device_code"}


def wait_for_approval(
    pending: dict[str, Any],
    *,
    profile: str | None = None,
    timeout: float | None = None,
    http: HttpFn = http_post_json,
    sleep: Callable[[float], None] = time.sleep,
    clock: Callable[[], float] = time.monotonic,
    on_tick: Callable[[], None] | None = None,
) -> dict[str, Any]:
    expires = _parse_iso(pending.get("expires_at")) or (_now() + timedelta(minutes=10))
    budget = max(0.0, (expires - _now()).total_seconds())
    if timeout is not None:
        budget = min(budget, timeout)
    deadline = clock() + budget
    interval = max(1, int(pending.get("interval") or 2))
    url = f"{pending['api_url']}/api/mcp-connect/token"

    while True:
        status, body = http(url, {"device_code": pending["device_code"]})
        state = body.get("estado")
        if status == 200 and state == "aprobada" and body.get("token"):
            hours = float(body.get("expires_in_hours") or pending.get("hours") or 24)
            expires_at = _now() + timedelta(hours=hours)
            mcp_url = body.get("mcp_url") or f"{pending['api_url']}/mcp"
            path = save_credentials(body["token"], mcp_url, expires_at, profile)
            pending_path(profile).unlink(missing_ok=True)
            return {
                "status": "approved",
                "credentials_path": str(path),
                "mcp_url": mcp_url,
                "expires_at": expires_at.isoformat(),
                "expires_in_hours": hours,
                "writes_enabled": body.get("writes_enabled"),
            }
        if status in (202, 429) or state == "pendiente":
            if clock() >= deadline:
                return {"status": "pending", **public_ticket(pending)}
            if on_tick:
                on_tick()
            sleep(interval * (2 if status == 429 else 1))
            continue
        pending_path(profile).unlink(missing_ok=True)
        if state == "denegada":
            raise StellarAuthError("The connection was denied in StellarCode.")
        raise StellarAuthError(f"Login failed (HTTP {status}, {state or 'error'}): {body.get('error') or body}. Run `devflow stellar-login` again.")
